### ISSUE TITLE
Move over code to this repo

### ISSUE THREAD

**Issue by aditya-konarde** [openshift/openshift-state-metrics#1]
Move code from https://github.com/wanghaoran1988/openshift-state-metrics to this repo https://github.com/openshift/openshift-state-metrics

We probably cannot follow https://help.github.com/en/articles/transferring-a-repository because it states: 

```
The target account must not have a repository with the same name, or a fork in the same network.
```

Will let @wanghaoran1988 decide :)

**Comment by wanghaoran1988** [comment]
I will do a code manual copy.

**Comment by aditya-konarde** [comment]
https://github.com/openshift/openshift-state-metrics/pull/2
