### ISSUE TITLE
Routes: Status when backing service is deleted/not present

### ISSUE THREAD

**Issue by aditya-konarde** [openshift/openshift-state-metrics#21]
Currently if I create a route pointing to an SVC, and then delete the backing SVC, there is no change at all in any of the metrics related to the route. 

From an alerting perspective, I would like to know if the route is 'healthy'. 

ToDo:
- Investigate how this is handled for Ingress in kube-state-metrics
- Implement a status metric for routes

**Comment by wanghaoran1988** [comment]
the openshift-state-metrics only expose detailed info of the "Route" object, if the "Route" object changed, the metrics will change, we should only expose raw data.

**Comment by ulikl** [comment]
The health/usability of the routes can be determined by
 haproxy_backend_up
from the HAProxy metrics endpoints of the Router pods.
