### ISSUE TITLE
Create manifest bundle

### ISSUE THREAD

**Issue by aditya-konarde** [openshift/openshift-state-metrics#23]
Use a `Template` file to bundle up all the manifests required, so that a user with cluster-admin can get started really quickly with an `oc create -f bundle.yaml`

**Comment by wanghaoran1988** [comment]
I'd like we can create a jsonate template, as our goal is to integrate this to openshift/cluster-monitor-operator, and this project is using jsonnet to integrate other components.
 https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/kube-state-metrics.jsonnet

**Comment by wanghaoran1988** [comment]
this is done.
/close
