### ISSUE TITLE
OpenShift version requirements

### ISSUE THREAD

**Issue by klenje** [openshift/openshift-state-metrics#42]
Hi,
I don't find any info on which is the minimal version of OpenShift required for openshift-state-metrics.
Is it working with OpenShift 3.7?

Thanks

**Comment by wanghaoran1988** [comment]
This is officially supported in openshift 4.2.

**Comment by klenje** [comment]
for information, it works fine on OpenShift 3.11, just a minor change needed (removal of nodeSelector in Deployment)
