### ISSUE TITLE
Document currently exposed metrics and their cardinalities

### ISSUE THREAD

**Issue by aditya-konarde** [openshift/openshift-state-metrics#6]

**Comment by aditya-konarde** [comment]
@BlueShells and @wanghaoran1988 did some amazing work on this here: https://github.com/openshift/openshift-state-metrics/pull/18

We're currently inline with what Kube-state-metrics provides. We should decide whether we want to list the cardinality of each time series or that should be left for the users.

**Comment by wanghaoran1988** [comment]
this was done. /close
